language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:

    # submit coverage report
    - if [[ "$MATLAB_VER" == "R2018b" && "$ARCH" == "Linux" ]]; then
      bash <(curl -s https://codecov.io/bash) -f "!*.lst";
      fi
